### ISSUE TITLE
Feature request: Zoom into map and to current position automatically

### ISSUE THREAD

**Issue by Elmi77** [DaylightingSociety/WhereAreTheEyes#22] opened 2016-12-06 08:10 UTC
It would be really nice when the map shown in the App would not display the whole earth but zoom to a (predefinable) zoom-level and to the users current position. This makes it much easier to verify if the current position is really correct or if one should not register a camera because GPS is currently hundreds of metres away from the real position.

**Comment by milo-trujillo** [comment] 2016-12-06 17:04
This is default behavior if the app has been given location access. We may not be able to zoom to user location on first startup if we don't have location permissions, but will do so on all future app openings. If the app is in the background and pulled to the front we re-center the map, but do not re-zoom it.

Am I understanding you correctly? I want to make sure we haven't just miscommunicated before I close the issue.

**Comment by Elmi77** [comment] 2016-12-07 06:17
I'm running the version from F-Droid and it definitely does not zoom into the map/keep the current position. It always starts and stays with the whole-earth view. So I always have to zoom in to my position manually - and I have to drag the map manually when my position has moved out of the current view.

**Comment by milo-trujillo** [comment] 2016-12-07 19:00
That's interesting. I just wiped my device, installed from F-Droid, and it zoomed to my location on startup. It also re-centers correctly when the app is resumed, or I go to the help page and back. Are you sure you've given the device location permissions?

**Comment by Elmi77** [comment] 2016-12-09 06:21
Yes, it has location permissions, when I zoom into the map manually, I can see the correct one. I tried again, now also with a valid GPS-fix before the app was started...but nothing, I only get the whole-earth-view...

**Comment by milo-trujillo** [comment] 2016-12-09 09:32
Fascinating. I'm unable to reproduce this, I'll try to get a few other people testing.

**Comment by elKaZe** [comment] 2017-03-18 03:38
I have too manual zoom too

**Comment by milo-trujillo** [comment] 2017-05-16 07:29
As of the latest code, so do I. This appears to be a race condition between the GPS code and the map initialization code - if we have a location update ready before the map is initialized then the map will auto-scroll and zoom to the location. A recent re-ordering of some lines made the race condition much more noticeable. Correct behavior *should* be scrolling the map appropriately once we get our first location update.

This will be fixed in the next release.

**Comment by milo-trujillo** [comment] 2017-07-04 19:25
This is now partially-resolved, but not well. In the simulator the app correctly scrolls to my location once the first location update comes in, but on my physical tablet it does not. The app *does* scroll to location on both devices if you call up another activity (like the help screen) and return to the main screen. The map does not auto-zoom.

Help solving this would be appreciated, since the main features I'll be working on are #7 and #3.

**Comment by milo-trujillo** [comment] 2017-07-04 19:27
Would #17 make this a non-issue? I prefer it to auto-zooming and scrolling in some regards, since it means the map won't move out from under the user unless they ask it to. Thoughts?

**Comment by KidPluto** [comment] 2017-07-24 16:14
This is the very first thing I noticed, that each time I open the app I need to spend 2 minutes zooming into where I am.  The world map which comes up when opening the app knows where I am.  But I need to manually zoom in. 
Android MotoG4
Thanks.

**Comment by milo-trujillo** [comment] 2017-10-22 20:46
This is implemented on the 1.4 branch via issue #17, and will be in the next release.

**Closed as completed by milo-trujillo** 2017-10-22 20:46 UTC
Labels: bug, help wanted, Android
