### ISSUE TITLE
Confirmation by same user

### ISSUE THREAD

**Issue by alcharkov** [DaylightingSociety/WhereAreTheEyes#4] opened 2016-10-24 12:40 UTC
Hi, when the camera location added, then it can be confirmed by same user which adds it.

**Comment by milo-trujillo** [comment] 2016-10-24 13:13
Can you explain what you mean? A user can both mark a camera on the map _and_ verify it's existence?

**Comment by alcharkov** [comment] 2016-10-24 16:45
Yes, I can verify my own addition

**Comment by milo-trujillo** [comment] 2016-11-21 16:23
I have been unable to reproduce this problem. I assume the steps are:

* Mark a new camera
* View that confirmations are at "1"
* Try to mark a new camera at the same location
* View that confirmations are now at "2"

Instead I get the expected behavior, that the new camera remains at one confirmation, and the server ignores my second mark. I am going to close this issue unless it is confirmed by another user.

**Closed as completed by milo-trujillo** 2016-11-21 16:23 UTC
