### ISSUE TITLE
Failure in submission of camera due to wrong Geo-IP information

### ISSUE THREAD

**Issue by Elmi77** [DaylightingSociety/WhereAreTheEyes#39] opened 2017-06-02 06:11 UTC
I recently tried to submit a bunch of cameras but the App rejected them with an error message (Your current location does not fit to the location of the IP" (or something like this).

So it seems you are checking the GPS location against the IP location using an inaccurate or outdated Geo IP database or with some too strong settings.

I have been within Munich using the IP of a big German mobile data provider, so there was nothing mysterious or wrong with my location.

**Comment by milo-trujillo** [comment] 2017-06-02 06:15
How recently was this? Are you still seeing the error? On Tuesday we realized we'd accidentally re-activated the geoip code, and promptly removed it. Entirely my fault, but fortunately a problem on the server side that could be quickly fixed. Everything should have been working since Tuesday.

**Comment by Elmi77** [comment] 2017-06-02 06:20
It was a few days ago and happened several times during this day. I would have to re-check if the problem still exists...

**Comment by milo-trujillo** [comment] 2017-06-02 06:28
Alright. I'm unable to reproduce the error, so I'm going to close the issue unless you continue to have the problem.

Thanks for bringing this back to my attention, the geoip code has now been removed instead of disabled, to prevent this from happening again. Sorry about that.

**Closed as completed by milo-trujillo** 2017-06-02 06:28 UTC
Labels: bug, cannot-reproduce, server
