### ISSUE TITLE
Adds camera without confirmation

### ISSUE THREAD

**Issue by senorwafflez** [DaylightingSociety/WhereAreTheEyes#5] opened 2016-10-25 07:53 UTC
In the app for iOS, I can add camera locations without confirmation.
Even though the setting for confirmation is switched on.

**Comment by milo-trujillo** [comment] 2016-10-25 15:16
In the simulator and on our test devices the confirmation works as intended, but several people have pointed out that it isn't working for them. We will get to the bottom of it as quickly as possible.

**Comment by senorwafflez** [comment] 2016-10-25 15:19
It happened the first couple of times I used the app.
Now it asks for confirmation like it should. Doesn't seem to be quite consistent.
First time use bug perhaps, or just intermittent.

**Comment by milo-trujillo** [comment] 2016-10-25 15:22
My guess is it's a problem with the Settings bundle. Something like "default state for confirmations is disabled, unless you actually go look at the state, which sets it to true." That could explain why our tests haven't turned it up. Should be fun to debug.

It _could_ be intermittent, but the confirmations work consistently for me, and several people have mailed in saying the confirmation didn't work on their device.

**Comment by milo-trujillo** [comment] 2016-10-28 00:25
Got it. The 'Default Value' setting in the app plist only effects what state Settings shows at app start, _not_ the initial state inside code. Needed to add a function call to set the correct defaults at app start:

``` obj-c
    NSDictionary *userDefaultsDefaults = [NSDictionary dictionaryWithObjectsAndKeys:
                                          [NSNumber numberWithBool:YES], kConfirmMarkingCameras,
                                          [NSNumber numberWithBool:NO], kShowScore,
                                          nil];
    [[NSUserDefaults standardUserDefaults] registerDefaults:userDefaultsDefaults];
    [[NSUserDefaults standardUserDefaults] synchronize];
```

I'll post the changes to this repo and close the issue as soon as Apple accepts the new version.

**Comment by milo-trujillo** [comment] 2016-11-10 23:25
New version (1.2) has been released, fixes the 'Default Value' problem.

**Closed as completed by milo-trujillo** 2016-11-10 23:25 UTC
Labels: bug, iOS
